### ISSUE TITLE
Website Certificate expired

### ISSUE THREAD

**Issue by SiC42** [tiddlydrive/tiddlydrive.github.io#11]
Your certificate for your website lordratte.info expired, which could cause confusion with inexperienced users, as the browser will print huge warnings.
This, of course, is not a direct problem with the tiddlydrive, but I didn' know where to post this instead.

**Comment by LordRatte** [comment]
Please see https://twitter.com/Lord_Ratte/status/1085157632799895552?s=09

When I eventually get hold of a computer, I will put some notices up on my site and the app.

**Comment by beerendlauwers** [comment]
Well that sucks :( Do you happen to have a Patreon?

**Comment by LordRatte** [comment]
Yeah. I agree. An ungraceful collapse of a favourite project is hardly how
I want to start the year.

I don't have Patreon. In terms of monetization for this project, I had a
bitcoin address in the about section of the app (for tips). I might have
looked into Patreon as an additional method if enough people had expressed
interest in donating to support development and server maintainence — which
never happened.

**Comment by beerendlauwers** [comment]
Seems to be working again now. What does the Tiddly Drive server have to be running? Can we provide backup servers that users can add to a list in the extension? I have some cloud computing resources available as well.

**Comment by ogrotten** [comment]
> Can we provide backup servers that users can add to a list in the extension? I have some cloud computing resources available as well.

I also have server resources as well that I could donate, free as in beer, to the ongoing bits of the project.

@LordRatte there are internet communities out there that will help. It sucks that I just sent a literal stack of old but unused computers to recycling. But I guarantee that there's someone out there with a vested interest that would be willing to "help" in some way.

Please let me know if you'd like to take advantage of my offer. Free for as long as my formerly-phat server is hosted... which has been I think 6 yrs now, of which I don't foresee an end.

**Comment by LordRatte** [comment]
@ogrotten The problem was renewing the certificate monthly. I have done a workaround and everything is back up under an new domain name.

Please see:
https://twitter.com/Lord_Ratte/status/1134469005085949957
