### ISSUE TITLE
404 while using Firefox

### ISSUE THREAD

**Issue by srbriker** [tiddlydrive/tiddlydrive.github.io#16]
Late last week I began getting 404 Page Not Found while using Firefox. I have not tried Chrome.

**Comment by LordRatte** [comment]
Seems fine for me. Please confirm that you're using. https://tiddlydrive.github.io/ instead of the old site.

If you are, please can you send a screenshot and tell me what version of Firefox you have?

**Comment by srbriker** [comment]
I did not realize that there was a new site. Let me try that first.

Steve
