### ISSUE TITLE
Reference to files

### ISSUE THREAD

**Issue by dioclecio** [tiddlydrive/tiddlydrive.github.io#2]
Dear sirs, 

how could I make a reference to files in subfolders?

For example: 
![captura de tela 2017-12-06 as 14 34 03](https://user-images.githubusercontent.com/1454277/33672940-a7a3e514-da92-11e7-9323-d6aeaa6b421f.png)

In this case, the command [img[img/teste001.png]] doesn't work.

![captura de tela 2017-12-06 as 14 35 57](https://user-images.githubusercontent.com/1454277/33673011-d2ac28b6-da92-11e7-90fb-846e3f744a34.png)

![captura de tela 2017-12-06 as 14 36 04](https://user-images.githubusercontent.com/1454277/33673031-d8dec84c-da92-11e7-87ce-7b8d4851b5f4.png)

Should I have to Embed the file? And In case of PDF or DOC files?

Yours.

Dino

**Comment by LordRatte** [comment]
Hi, @dioclecio. This is unfortunately a limitation of how the app is set up to use the Google Drive API. It is potentially possible to make this work yet that would require users to accept permissions that allow the app to access anything in one's Google Drive.
