### ISSUE TITLE
Unable to load HTML with Brave

### ISSUE THREAD

**Issue by srbriker** [tiddlydrive/tiddlydrive.github.io#20]
I am unable to load my HTML with Brave this morning, though it worked fine yesterday. It just continues to try loading. I have verified that everything is still functioning properly on Firefox and Chrome, but Brave is being persnickety.

**Comment by LordRatte** [comment]
The app doesn't officially support Brave. If you can get someone to debug it, they are welcome to make a pull request to apply the update.
