### ISSUE TITLE
Entries not saving

### ISSUE THREAD

**Issue by aagha** [tiddlydrive/tiddlydrive.github.io#25]
I've setup per the instructions but note that if I create an entry, I do get a message that my entry has saved:

![image](https://user-images.githubusercontent.com/5522103/75726334-fdbb9400-5c96-11ea-83e0-2e64ef23c195.png)

However, when I reload the page, the entry is gone:

![image](https://user-images.githubusercontent.com/5522103/75726366-14fa8180-5c97-11ea-921a-18e937f1b1ae.png)

Any idea why?

**Comment by aagha** [comment]
Ping

**Comment by emarsk** [comment]
Same here. It used to work, but now it doesn't. No error, no feedback, it just doesn't save. I have to use the download saver and re-upload the file manually.

**Comment by emarsk** [comment]
Should we assume this project is dead?

**Comment by LordRatte** [comment]
Please upload an example of a tiddlywiki file and a screen shot of the test tiddler you created (like the top picture) or let me know if it is no longer a problem.

**Comment by emarsk** [comment]
It appears to work, now. Thanks.
