### ISSUE TITLE
403 error when authenticating with a supervisioned google account

### ISSUE THREAD

**Issue by rjack** [tiddlydrive/tiddlydrive.github.io#26]
My daughter is trying to add Tiddly Drive to her drive account, but she gets this error:

```
Errore 403: access_denied
Richiedi dettagli

    redirect_uri=storagerelay://https/tiddlydrive.github.io?id=auth133736
    response_type=permission id_token
    openid.realm=
    client_id=292510858390-7md8cr4332ppas1hcoccj7g1j24i9iqg.apps.googleusercontent.com
    ss_domain=https://tiddlydrive.github.io
    fetch_basic_profile=true
    gsiwebsdk=2
    access_type=online
    display=page
    scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/drive.file
```

With other regular google accounts I don't get this error, maybe it's related to the fact that my daughter's account is supervisioned?

How can I enable Tiddly Drive for her? I already tried to lower any resctriction in the family settings.

Thanks!

**Comment by LordRatte** [comment]
Is the TiddlyWiki file in her "My Drive" folder and set to be owned by her?

**Comment by LordRatte** [comment]
Stale thread.
