### ISSUE TITLE
"Unknown Error" while saving

### ISSUE THREAD

**Issue by oldnaari** [tiddlydrive/tiddlydrive.github.io#27]
Have the following error today. Yesterday it worked fine

![image](https://user-images.githubusercontent.com/31252576/90719292-05aed500-e2c5-11ea-943d-cbac676fbd1a.png)

Tried following, didn't help:
* Checked Internet (everything ok)
* Reloaded the page

**Comment by oldnaari** [comment]
Today it started to work properly. I think this issue may be closed

**Comment by LordRatte** [comment]
If it happens again, can you please paste the contents of your Javascript console?
To open it, press either **F12** or
**Command+Option+J** (Mac) or
**Control+Shift+J** (Windows, Linux, Chrome OS)
