### ISSUE TITLE
Bookmarks stop working after a while.

### ISSUE THREAD

**Issue by Griffork** [tiddlydrive/tiddlydrive.github.io#28]
Reopening a tiddlywiki using a url (in my case I'm actually using a pinned tab and refreshing it) causes a domain error and says https://tiddlydrive.github.io/ cannot be found. I have this quite regularly, it seems to resolve itself after I open the wiki directly through Google Drive, so I think it might be an authentication issue?

![image](https://user-images.githubusercontent.com/3665998/98065306-74ed9b80-1ea8-11eb-8221-81b5c8339648.png)

Device details: Chrome 86, Windows 10

Steps to reproduce (may not be the most reliable):

1. Open Tiddlywiki in a chrome tab and leave it open.
2. Wait 24 hours (or longer?) after initially opening the wiki (you may need to restart your PC or force close + open chrome to trigger auth expiry).
3. Refresh the tiddlywiki page.

This didn't happen a year ago, the bug's started occurring since then. I suspect google updated their authentication security or something to be more secure which is messing with tiddlywiki.

**Comment by LordRatte** [comment]
This is not a problem with Tiddly Wiki. There is a misconfiguration on your workstation.

Search DNS_PROBE_FINISHED_BAD_CONFIG to learn how to fix this.
