### ISSUE TITLE
Installation info link leads to 404

### ISSUE THREAD

**Issue by aliengeo** [tiddlydrive/tiddlydrive.github.io#30]
There's a link on the Tiddly Drive page that says it leads to an info page with detailed install instructions. It's the link pictured here:
![Screenshot_2021-01-03 Tiddly Drive](https://user-images.githubusercontent.com/34959047/103475568-d7adc700-4d73-11eb-972b-dae1ec47e3ae.png)
It leads to `https://lordratte.gitlab.io/tiddlydrive` which appears to be dead. I wondered if it might be a link to `https://lordratte.gitlab.io/code/tiddlydrive` which simply hadn't been updated, but this is also a 404. I can't repair it with an updated link because I don't know where to find the most current information. Consequently, I also can't install Tiddly Drive.

**Comment by LordRatte** [comment]
I have fixed this. Thanks for logging it.
