### ISSUE TITLE
Works in one Google Drive account but not in another one

### ISSUE THREAD

**Issue by GradelerM** [tiddlydrive/tiddlydrive.github.io#31]
I have two Google Drive accounts : one main (connected to Firefox too) and one secondary. I'm using Firefox.
TiddlyDrive works fine in the main Google Drive, but not in the second one. I get a **"There was an error downloading the file"** message :

![image](https://user-images.githubusercontent.com/55435870/103823067-95d19900-5071-11eb-9f1d-f8d2cb97fcc5.png)

I tried the same thing with the Google Chrome browser... and now the secondary account works fine with it but the main doesn't.
The only difference is the following : when I first launched the TiddlyDrive app on each browser, I had an error message asking for allowing pop-ups. I allowed them with the main account on Firefox, and with the secondary account on Google Chrome.

Moreover, when I install TiddlyWiki on the second account, I don't have any pop-up to allow the app. I think this might be the problem.

Please, how do I allow TiddlyDrive on both my accounts so I can have TiddlyWikis on the main and the secondary one ?

**Comment by LordRatte** [comment]
The app hasn't been tested using two accounts at once. You can try using Firefox containers to log into separate accounts simultaneously.
