### ISSUE TITLE
The "TiddlyDrive Settings : News" dialogue causes a "privacy concern for me"

### ISSUE THREAD

**Issue by pmario** [tiddlydrive/tiddlydrive.github.io#35]
The line: https://github.com/tiddlydrive/tiddlydrive.github.io/blob/master/index.html#L167 loads a 3rd party widget.js, that is known to track users. ... There is some code, that pings the 3rd party site. ... 

With my browser settings it is blocked, but that may not be true for every user. 

So my suggestion is, that 

 - the "News tab" should only contain a link to the official twitter account. It isn't necessary, to show it inline
 - _NO_ 3rd party code should be loaded, so users are not tracked without confirmation

Tracking users without consent isn't allowed due to the [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) rules. The code I did mention does exactly that. So please fix it as suggested.

**Comment by LordRatte** [comment]
The development version actually already has this feature. Feel free to test it and provide feedback to speed up the testing process. You can access the development version by replacing `tiddlydrive.github.io/` with `tiddlydrive.github.io/development/` in your address bar to access the development server.

**Comment by pmario** [comment]
Yea, I do like the dev-version. .. The styling of the "News" tab could be improved, but I do like that there is no tracking anymore.

**Comment by pmario** [comment]
I did also test the page with FireFox. For me it seems everything works as expected. ... Is there anything, which could "break" the wiki if FF is used?

**Comment by pmario** [comment]
Do you want to have more "unrelated feedback" here or should I open new issues for them

**Comment by LordRatte** [comment]
Thanks. Once I've double-checked that it's good to go, I'll apply the update.

If you have any more feedback about a new breaking bug or a security vulnerability on Chrome or Firefox, you may open a new issue.

**Comment by pmario** [comment]
I've seen, that you merged the dev-branch. I do like that!
