### ISSUE TITLE
2 permanent redirects seem to cause a 600ms delay

### ISSUE THREAD

**Issue by pmario** [tiddlydrive/tiddlydrive.github.io#36]
There seems to be 2 requests that are 301-permanent-redirect ... that seem to cause a 600ms delay. 

![grafik](https://user-images.githubusercontent.com/374655/123141971-40d7e280-d459-11eb-9f51-5069c3c66669.png)

The images come from shields.io ... IMO this info should be part of the About page under "Services Used" with a short description who they are. .. I had to search the internet to find out who they are

**Comment by LordRatte** [comment]
Check your screenshot again. It's 130 ms because of the redirect.
