### ISSUE TITLE
3rd-party overhead is about 460kByte for 1 config dialogue with 3 settings and 3 tabs

### ISSUE THREAD

**Issue by pmario** [tiddlydrive/tiddlydrive.github.io#37]
Did you ever consider to avoid the 3rd-party libs or replace them with smaller libs?

I didn't have a closer look, which jquery functions are actually used. .. BUT I'm pretty sure that materialize.js is overhead atm, since the fonts don't load anyway. IMO installing web-fonts for a setting dialogue is a bit of an overkill.

**Comment by LordRatte** [comment]
Feel free to block the fonts you don't want with a user-script.
