### ISSUE TITLE
Is this supposed to work in Sept. 2021?

### ISSUE THREAD

**Issue by tazmo** [tiddlydrive/tiddlydrive.github.io#41]
Been trying to get this to work when selecting "open with" in gdrive on a completely empty, new tiddlywiki.

Installed/uninstalled gdrive Tiddlydrive many times.
Turned off uBlock Origin.
Turned off Privacy badger.

Read your blog. I realized you moved the extension to be hosted at:
https://tiddlydrive.github.io/

Have clicked the config wheel on bottom right hand corner to re-authitcate many times. Does not help.

The tiddlydrive.github.io site just "spins" the bar along the top and does not load the empty.html tiddlyfile from my gdrive.

It also does not seem to register as a 3rd party app in my Google account -> NO MATTER WHAT I DO.
I even went into my Google account and turned on "Less Secure Apps" in the security section -> STILL DOES NOT WORK and DOES NOT REGISTER as a 3rd Party app.

Actually, the app/plugin never registers.

I would really like this to work.

Any more ideas would be appreciated.
Thanks.

**Comment by tazmo** [comment]
Even cleared my cookies each time above too... still didn't work.

Note the Certificate used is for github.com, not github.io. Not sure if that would make a difference *for the plugin* or not.

**Comment by tazmo** [comment]
Chrome DevTools console output log.

[tiddlydrive.github.io-1632501158025.log](https://github.com/tiddlydrive/tiddlydrive.github.io/files/7227226/tiddlydrive.github.io-1632501158025.log)

**Comment by LordRatte** [comment]
I suggest you double check Privacy Badger and any other plugins or settings that block cross-origin cookies. This happens when you authorize with Google in the popup but by the  time  you get back to TiddlyDrive, the cookies have been deleted and you are still considered unauthorized.

**Comment by cosmaioan** [comment]
I can confirm that works. But I installed some time ago.
Great tool

**Comment by tazmo** [comment]
Okay... somehow over the last couple of months, it started working.

Bad thing is, I have no idea what I did to get it to work.

So if anyone runs across this in the future, tiddlydrive appears to be working at the end of CY 2021.
