### ISSUE TITLE
TiddlyDrive App not found

### ISSUE THREAD

**Issue by willw1** [tiddlydrive/tiddlydrive.github.io#43]
Following steps on install page, step 4 does not give the app, but instead a message "We couldn't find anything for your search."
Chrome web store says the app is "No longer available".

**Comment by PhantomPCH** [comment]
I'm also facing the same issue here. Would really appreciate it to get this resolved quickly as I've seen this extension highly recommended by other Tiddlywiki users. 😊

**Comment by andreadelprete** [comment]
Same problem here

**Comment by RicingFX** [comment]
I am in the same situation. Sadly the project seems to be kinda dead. Last interaction here and on twitter was last year. I hope I am not right with my assumption as I'd love to test the Drive-Integration.

**Comment by LordRatte** [comment]
Likely relevant to this:
https://github.com/tiddlydrive/development/blob/master/eol_notice.md
